name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
  # cron job for 7:50am to coincide with 11:50pm Vancouver time
    - cron:  '50 7 * * *'

jobs:
  scheduled:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        today=$(date +"%Y-%m-%d")
        echo "Today is $today"
        year=$(python -c "from Daily_Totals.get_date import *;date_to_year('$today')")
        scoringId=$(python -c "from Daily_Totals.get_date import *;date_to_scoringId('$today')")
        echo "Year is $year and scoringId is $scoringId"
        curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[0,6,1,2,4]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[$scoringId]},"sortAppliedStatTotal":null,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":2,"value":$scoringId},"sortStatId":null,"sortStatIdForScoringPeriodId":null,"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":9950}}'| jq . > Actions_Scrape/Skater_log.json
        echo "curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[0,6,1,2,4]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[$scoringId]},"sortAppliedStatTotal":null,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":2,"value":$scoringId},"sortStatId":null,"sortStatIdForScoringPeriodId":null,"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":9950}}'| jq . > Actions_Scrape/Skater_log.json"
        curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[5]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[$scoringId]},"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":1000,"offset":0,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":1,"value":$scoringId},"filterRanksForScoringPeriodIds":{"value":[$scoringId]},"filterRanksForRankTypes":{"value":["STANDARD"]}}}' | jq . > Actions_Scrape/Goalie_log.json
        echo "curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[5]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[$scoringId]},"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":1000,"offset":0,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":1,"value":$scoringId},"filterRanksForScoringPeriodIds":{"value":[$scoringId]},"filterRanksForRankTypes":{"value":["STANDARD"]}}}' | jq . > Actions_Scrape/Goalie_log.json"
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=":America/Vancouver" date)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
