name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '50 23 * * *'

jobs:
  scheduled:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/2024/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[0,6,1,2,4]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[90]},"sortAppliedStatTotal":null,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":2,"value":90},"sortStatId":null,"sortStatIdForScoringPeriodId":null,"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":9950}}'| jq . > Actions_Scrape/Skater_log.json
        curl 'https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/2024/segments/0/leagues/59311?view=kona_player_info' -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[5]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":[90]},"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":1000,"offset":0,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":1,"value":90},"filterRanksForScoringPeriodIds":{"value":[90]},"filterRanksForRankTypes":{"value":["STANDARD"]}}}' | jq . > Actions_Scrape/Goalie_log.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
