name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
  # cron job for 9:50am to coincide with 2:50am PDT or 1:50pm PST Vancouver time
    - cron:  '50 9 * * *'

jobs:
  scheduled:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        # get yesterday's date
        yesterday=$(TZ=":America/Vancouver" date -d '-1 day' +"%Y-%m-%d")
        echo "Yesterday was $yesterday"
        year=$(python -c "from Daily_Totals.get_date import *;date_to_year('$yesterday')")
        scoringId=$(python -c "from Daily_Totals.get_date import *;date_to_scoringId('$yesterday')")
        echo "Year is $year and ScoringId is $scoringId"
        if [[ $scoringId == -1 ]]; then echo "Yesterday's date appears to be offseason so it will be skipped" && exit 0;
        curl "https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info" -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[0,6,1,2,4]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":['"$scoringId"']},"sortAppliedStatTotal":null,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":2,"value":'"$scoringId"'},"sortStatId":null,"sortStatIdForScoringPeriodId":null,"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":9950}}' | jq . > docs/dailies/"$year"/skaters/"$yesterday".json
        curl "https://lm-api-reads.fantasy.espn.com/apis/v3/games/fhl/seasons/$year/segments/0/leagues/59311?view=kona_player_info" -H 'X-Fantasy-Filter: {"players":{"filterSlotIds":{"value":[5]},"filterStatsForCurrentSeasonScoringPeriodId":{"value":['"$scoringId"']},"sortPercOwned":{"sortPriority":3,"sortAsc":false},"limit":1000,"offset":0,"sortAppliedStatTotalForScoringPeriodId":{"sortAsc":false,"sortPriority":1,"value":'"$scoringId"'},"filterRanksForScoringPeriodIds":{"value":['"$scoringId"']},"filterRanksForRankTypes":{"value":["STANDARD"]}}}' | jq . > docs/dailies/"$year"/goalies/"$yesterday".json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=":America/Vancouver" date)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
